#!/usr/bin/bash

usage() {
    echo
    echo "Usage: buildabs PACKAGENAME"
    echo
    echo "Checks the ABS for a given package."
    echo "It will install necessary dependancies and remove them after installation."
    echo
    exit 0
}

package=$1

packagepath=`find /var/abs/ -name $package`

if [ -n $package ] && [ -n $packagepath ]; then
    echo "Found package at $packagepath"
    info=`/usr/bin/pacman -Si $package | grep -i version`
    echo "Current repo version is: $info"
    pkgver=`cat $packagepath/PKGBUILD | grep pkgver=`
    pkgrel=`cat $packagepath/PKGBUILD | grep pkgrel=`
    echo "Package version is $pkgver"
    echo "Package release is $pkgrel"
    read -p "Would you like to build the package? (y/n) " isbuild

    if [[ ${isbuild,,} == 'y' ]]; then
	echo "Copying $package from $packagepath to /tmp for building"
	cp -r $packagepath /tmp/$package
	echo "Changing directory to /tmp/$package"
	cd /tmp/$package
	echo "Running makepkg -rsi on $package"
	echo "To cancel, press ^C (CTRL + C)"
	makepkg -rsi
	echo
	echo "Removing the build directory"
	sudo rm -r /tmp/$package
    else
        echo "Exiting now"
	exit 1
    fi
else
    echo "Package or packagepath is empty!"
    echo "Exiting now"
    exit 1
fi
